### ISSUE TITLE
Thank you for this gem.

### ISSUE THREAD

**Issue by kapoorlakshya** [mysterysci/rubocop_lineup#15]
Not an issue. Just wanted to thank you, @chrismo, for creating this gem. I have been using a pre-commit hook for a while now, but this gem seems like a better option than:

```bash
git ls-files -m | xargs ls -1 2>/dev/null | xargs rubocop -x
```

Feel free to close this.

**Comment by chrismo** [comment]
🎉 yay - thanks for the kind word!
